### PR TITLE
refactor: harmonize bash scripts

### PR DESCRIPTION
**Pull request by jandom**
Make the bash scripts consistent in terms of error handling

### CODE REVIEW

**Comment by lilyminium** [comment]
Thanks @jandom, these all look like good improvements and it's failing as it should. I think that `deploy_docs_via_travis.sh` is actually redundant and should be deleted now -- we moved on from Travis a while ago and at least in the user guide no longer use it for CI or deployment.

I'd hold off on approving/merging until #275 is done so we can check that it also succeeds when there's no error.

**Comment by jandom** [comment]
Thanks @lilyminium , removed the travis deploy script now – thanks for the pre-review!

**Comment by jandom** [comment]
@lilyminium PTAL this should be ready to go now, not blocked by anything

**Review by lilyminium — APPROVED** [review]
LGTM, thank you for this @jandom!

**Pull request merged**
