### PR TITLE
Remove hole.ipynb

### PR DESCRIPTION
**Pull request by IAlibay**

### CODE REVIEW

**Comment by IAlibay** [comment]
Turns out it's pretty much the exact same notebook as hole2.ipynb, so there's really not reason to keep it around? (unless I'm missing something)

**Review by lilyminium — APPROVED** [review]
I believe one was for `hole2` the module (revamped) and one was the now-deprecated `hole.py` analysis. Thanks!

**Comment by IAlibay** [comment]
whelp that was not meant to be targetting `master`

**Comment by IAlibay** [comment]
doesn't really matter anyways since we're ditching `master`, I'll open a separate one for `develop`

**Pull request merged**
