### PR TITLE
Add LGPL and CC-BY-SA LICENSE

### LINKED ISSUE #134: License for the user guide
So I might not be looking at the right place, but as far as I can tell the user guide doesn't directly declare any type of license.

I guess the assumption is that it inherits MDA's GPLv2 license?

Given that the user guide is a really good teaching resource, I think it might be good to make it clear as to what the license is so that folks can be more confident in using parts of it in derivative works where possible.

### PR DESCRIPTION
**Pull request by RMeli**
Fix #134.

@MDAnalysis/coredevs, thoughts? 

----
📚 Documentation preview 📚: https://mdanalysisuserguide--363.org.readthedocs.build/en/363/

### CODE REVIEW

**Comment by IAlibay** [comment]
The code bits can't be LGPL if they are derivatives of GPL, you'll have to wait until relicense

**Comment by RMeli** [comment]
> you'll have to wait until relicense

Yep, this was my assumption. It would be annoying to have to re-license here too.

**Review by orbeckst — CHANGES_REQUESTED** [review]
Looks good but I have to block until the MDA relicense to LGPL is done.

**Comment by RMeli** [comment]
Pinging since now the relicensing is done.

**Review by orbeckst — APPROVED** [review]

**Comment by orbeckst** [comment]
@lilyminium , as the original author of the UG, could you please als ok this license assignment?

**Review by lilyminium — APPROVED** [review]
LGTM!! Sorry for the holdup.

**Pull request merged**
