### PR TITLE
Add readthedocs config

### PR DESCRIPTION
**Pull request by lilyminium**
Add a .readthedocs file to build docs on ReadTheDocs

### CODE REVIEW

**Comment by lilyminium** [comment]
We settled on hosting our docs on Github and using Travis to build them in #67, but this would still be good as an easy way to demo branches when people make PR's

**Comment by lilyminium** [comment]
Pinging any of @MDAnalysis/coredevs for an opinion :-)

This config file *should* allow anyone on a fork to build RTD docs for their branch, which will make it much easier to review

**Comment by orbeckst** [comment]
That's a great idea. Can you add a mini-howto in https://www.mdanalysis.org/UserGuide/contributing_docs.html ?

**Comment by lilyminium** [comment]
I don't think users need to do anything, we can just turn on "build docs for pull requests" and a little check will appear down the bottom like in this one:

https://github.com/lilyminium/UserGuide/pull/1

which builds to: https://mdanalysisuserguide--1.org.readthedocs.build/en/1/

the "mdanalysis" name is already taken on RTD, I hope by one of us, but we can do this for the main repo as well with mdauserguide and mdadocs.

After this is merged I might take out the little section on "how to build your own gh-pages" part in the user guide and replace it with "look at the docs in your PR"

**Comment by orbeckst** [comment]
MDAnalysis on RTD is ours. 

> Am 11.06.2020 um 18:31 schrieb Lily Wang <notifications@github.com>:
> 
> the "mdanalysis" name is already taken on RTD, I hope by one of us, but we can do this for the main repo as well with mdauserguide and mdadocs.

**Comment by lilyminium** [comment]
I don't think I can add any MDAnalysis repos to RTD so someone else may have to check that this works

**Comment by orbeckst** [comment]
@dotsdl you took https://readthedocs.org/projects/mdanalysis/ – can you add @lilyminium @richardjgowers and myself as maintainers, please?

**Comment by lilyminium** [comment]
For example, in #76 I built the docs on RTD and could see that some of the code blocks didn't render; but this depended on me merging the PR into a branch on my own fork (so pushes won't automatically trigger re-building) and remembering to toggle it on at ReadTheDocs. Users can also make their own RTD versions but this can clog up the namespace (only so many versions of mdauserguide out there) and there are some minor things to do in settings.

It would be much more convenient for the user guide to get built on RTD automatically as part of the PR checks, like below:

Screenshot 2020-06-15 at 7 45 07 PM

**Comment by orbeckst** [comment]
This would be cool. What is needed to make the auto-RTD build work?

**Comment by dotsdl** [comment]
I've added @lilyminium, @richardjgowers, and @orbeckst as maintainers to the MDAnalysis project on readthedocs. Please let me know if this does or doesn't give you the access you need to make this work.

**Comment by lilyminium** [comment]
Thanks for adding us @dotsdl! Unfortunately I still can't add *this* repo to ReadTheDocs; I don't think I have the right permissions. Maybe if someone who's an Owner of the MDAnalysis org tries?

**Pull request merged**
