### PR TITLE
Contacts

### PR DESCRIPTION
**Pull request by lilyminium**
Update contacts notebooks

- squashed Last executed and Last updated into one line
- Removed special section for visualisation packages
- Added "see also"
- Changed 'selection' keyword to 'select'
- Added radius_cut_q to [this notebook](http://minium.com.au/UserGuide/examples/analysis/distances_and_contacts/contacts_native_fraction.html) and explained results more
- Added background section to [this notebook](http://minium.com.au/UserGuide/examples/analysis/distances_and_contacts/contacts_within_cutoff.html)
- Added bit more intro to [RST readme](http://minium.com.au/UserGuide/examples/analysis/README.html#distances-and-contacts)

### CODE REVIEW

**Comment by dottiejean** [comment]
> Update contacts notebooks
> 
> - squashed Last executed and Last updated into one line
> - Removed special section for visualisation packages
> - Added "see also"
> - Changed 'selection' keyword to 'select'
> - Added radius_cut_q to [this notebook]() and explained results more
> - Added background section to [this notebook]()
> - Added bit more intro to RST readme

**Comment by lilyminium** [comment]
Hi @dottiejean, welcome to MDAnalysis! Did you have thoughts on this PR? I think your comments may have been a bit mixed up :-)

**Comment by dottiejean** [comment]
I'm not totally understand what I am doing. Lol

**Comment by orbeckst** [comment]
@lilyminium do you want to report the baby bot? They have a menu on the message and a category for meat in a can.

**Comment by dottiejean** [comment]
I'm not really sure what to do here offer my 8nsights??

**Pull request merged**
