### PR TITLE
Remove widget states from notebooks

### PR DESCRIPTION
**Pull request by IAlibay**
I've gone ahead and cleared all the widget states from all the notebooks under `examples`. This reduces the total size of the `doc` files from 154 MB to 60 MB. 

As far as I'm aware this _shouldn't_ affect how the notebooks render, but someone please double check the RTD results.

### CODE REVIEW

**Comment by pgbarletta** [comment]
I did the same when I added the nbval testing. They seem to accumulate with each run.

**Comment by IAlibay** [comment]
> I did the same when I added the nbval testing. They seem to accumulate with each run.

they shouldn't be getting committed, I think it's more of a case that someone forgot to clear them after an update

**Comment by lilyminium** [comment]
I *think* this removes the ability to look interactively at NGLView widgets on rendered docs. However I think the benefits of keeping the interactivity is much outweighed by the costs of storage compared to, say, a gif.

**Comment by lilyminium** [comment]
And the huge diffs are a pain.

**Review by lilyminium — APPROVED** [review]
LGTM. Not sure how this will interact with #251 so I'll let you merge.

**Comment by lilyminium** [comment]
Actually I'll merge now so I can build off it and replace widgets with gifs.

**Pull request merged**
