### PR TITLE
Add new notebooks

### LINKED ISSUE #45: Finalise script behaviour
**Is your feature request related to a problem? Please describe.**
The user guide uses a number of scripts to make tables, page stubs, and so on. Should these be put in `conf.py` to get run every time the docs are built, or should they be manually run? If they are automatically executed, how does that work with widgets that require visualisation in the browser first? 

**Describe the solution you'd like**
*1. Automatic execution*
- Update `conf.py` and add comments explaining what's going on
- Either turn off automatic execution of notebooks with NGLview widgets, or work out if selenium is a solution on Travis
- Remind contributors to temporarily turn off automatic execution if they're using `sphinx-autobuild` or it will refresh to infinity

*or*
*2. Manual execution*
- Remind contributors to re-execute scripts in pull request template. Put them all in `generate_all.sh`

### LINKED ISSUE #99: sections to be added
## ANALYSIS
- [ ] align.AverageStructure
- [ ] HydrogenBondAnalysis
- [ ] hole2
- [ ] DensityAnalysis

## OTHER
- [ ] ParmEd
- [ ] Notebook execution scripts
- [ ] other scripts; add to conf.py

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #99
Fixes #45 
Related to #105 

These are largely notebooks I made earlier during GSOD and updated a little. However, the diffusion map notebook is new.

Links (forthcoming from RTD):

**New**

- [Diffusion map](https://mdanalysisuserguide--125.org.readthedocs.build/en/125/examples/analysis/reduced_dimensions/diffusion_map.html)
- [Hydrogen bond analysis](https://mdanalysisuserguide--125.org.readthedocs.build/en/125/examples/analysis/structure/hydrogen_bond_analysis.html)
- [Density analysis](https://mdanalysisuserguide--125.org.readthedocs.build/en/125/examples/analysis/volumetric/density_analysis.html)
- [Hole remix](https://mdanalysisuserguide--125.org.readthedocs.build/en/125/examples/analysis/polymers_and_membranes/hole.html)
- [ParmEd](https://mdanalysisuserguide--125.org.readthedocs.build/en/125/examples/other/parmed_sim.html)

**Slightly updated**

- [PCA](https://mdanalysisuserguide--125.org.readthedocs.build/en/125/examples/analysis/reduced_dimensions/pca.html#Principal-component-analysis)  (description)

Add to #112

### CODE REVIEW

**Review by orbeckst — COMMENTED** [review]
Sorry, only managed to look at 3 notebooks so far:

## hole2 notebook

- I would move some of the general HOLE description for the PDB section to the front, then say that you can either run it like the hole binary (PDB) or on a trajectory/Universe, just to make clearer why you'd do one or the other
- `MDAnalysis.analysis.hole.HOLE` -> `MDAnalysis.analysis.hole2.HOLE`
- `**tmp*/pdb_name.pdb**: `: not properly formatted

## Diffusion map
- "where the transitions between conformational states is not well-sampled" -> "where the transitions between conformational states are not well-sampled" (is -> are)

Just for the future: maybe we should use the [AdK Transitions DIMS Dataset](https://www.mdanalysis.org/MDAnalysisData/adk_transitions.html) for the DiffusionMap analysis – instead of a single DIMS trajectory? Might make the output clearer. 

Or even better, use a trajectory that shows repeated transitions between states – could be a small organic molecule or a fancy folding trajectory.

## PCA
- Reference to a general paper on PCA (like in DiffusionMap), e.g. (pretty much randomly pulled from my master bibtex file):
   - [1] A. Amadei, A. B. Linssen, and H. J. Berendsen, “Essential dynamics of proteins,” Proteins, vol. 17, pp. 412–25, Dec 1993.
   - [2] I. T. Joliffe, Principal component analysis. Springer Series in Statistics, New York: Springer, 2 ed., 2002.
   - [3] F. Sittel, A. Jain, and G. Stock, “Principal component analysis of molecular dynamics: on the use of cartesian vs. internal coordinates,” J Chem Phys, vol. 141, p. 014111, Jul 2014.
   - [4] F. Sittel and G. Stock, “Perspective: Identification of collective variables and metastable states of protein dynamics,” The Journal of Chemical Physics, vol. 149, no. 15, p. 150901, 2018.
- What is the warning "For best results, your trajectory should be aligned on your atom group selection before you run the analysis. Setting align=True will not give correct results in the PCA." about? If `align=True` in PCA does not do the right thing then we should remove it, shouldn't we?
- The projection equation `\mathbf{r}_i(t) = \mathbf{w}_i(t) \times \mathbf{u}_i + \mathbf{\overline{r}}` uses "x" for the outer product. This seems prone to misinterpretation. Maybe write it out with explicit sums or use a different symbol (not the "cross product").

**Comment by lilyminium** [comment]
Thanks for the review, @orbeckst! I edited the things you mentioned, although I may leave migrating the DiffusionMap dataset for the future.

> What is the warning "For best results, your trajectory should be aligned on your atom group selection before you run the analysis. Setting align=True will not give correct results in the PCA." about? If align=True in PCA does not do the right thing then we should remove it, shouldn't we?

This is from 0.20.1 -- it has been fixed for 1.0.0. I remove this warning in #120.

**Review by orbeckst — COMMENTED** [review]
Continuation review... still not done (but wasted more time on 3D contour plotting than I'd care to admit...)

## ParmEd
Very nice, didn't find anything.

The OpenMM part is a bonus and shows how MDA is useful in analysis.

## Density
Very useful example with the PBC. 
- nice to have: embedded image of the `view1` and `view2` of the system
- GROMACS trjconv argument in the table comes as a surprise. Add a sentence **with a link** to the `gmx trjconv` program _before the table_ to note that these are operations commonly performed with gmx trjconv. Btw, what are the equivalent operations in VMD/pbc util or cpptraj? – @IAlibay ?
- link to docs for on-the-fly transformations
- Instead of calculating your own midpoints, use `dens.density.midpoints`. In general, I'd use the `Density` object, which is the result of the analysis instead of private attributes of `DensityAnalysis`
- I have more suggestions for 3D plotting in https://gist.github.com/orbeckst/a6a61c8f20a434c1c7520cd51c281522 (including nglview density and matplotlib surface contours, mostly based on https://stackoverflow.com/a/35472146

**Review by orbeckst — COMMENTED** [review]
Continuation review ... and final notebook:

## H-bond analysis
- An introductory sentence on what is generally considered a hydrogen bond would be nice.
- add link to API docs (I'd prefer if all mentioning of MDAnalysis objects such as `MDAnalysis.analysis.hydrogenbonds.HydrogenBondAnalysis` linked to the docs but presumably there's not markup in the notebooks equivalent to the sphinx roles that enable intersphinx linking?)
- The conditions for guessing were clearly spelled out – better than in the API docs! Is there a way for a user to create a list of all donors/acceptors that were considered for their system, e.g., so that they can check that whatever they think ought to be included is actually included (e.g., Methionine S_delta as acceptor (Gregoret et al, Proteins 9 1991, doi:[10.1002/prot.340090204.](https://doi.org/10.1002/prot.340090204)))?
- `update_selections` should be explained and point out that performance can be increased with `False` **if** the groups are static.


## SUMMARY

Great content, we just need to make sure that users find it!

**Comment by lilyminium** [comment]
@orbeckst thanks for the reviews and sorry for taking months to get back to you. In the interest of not forgetting about this for more months, I might merge tomorrow morning unless new changes are requested.

**Comment by orbeckst** [comment]
No problem.  Merging sounds good to me.

**Pull request merged**
