### PR TITLE
fix links in transformations

### LINKED ISSUE #178: broken link to "transformations tutorial"
**Describe the bug**
In the 1.0.0, 2.0.0 and 2.0.0-dev version of the user guide the page https://userguide.mdanalysis.org/2.0.0-dev0/trajectories/transformations.html says 

> Please see the full tutorial for more information.

but the link underneath it

https://userguide.mdanalysis.org/2.0.0/trajectories/examples/transformations/center_protein_in_box.ipynb#Doing-all-this-on-the-fly

is broken.

**Expected behavior**
Link should send me to the tutorial https://userguide.mdanalysis.org/2.0.0/examples/transformations/center_protein_in_box.html#Centering-in-the-box

**Actual behavior**
Link is broken. I can't find the promised tutorial.

### PR DESCRIPTION
**Pull request by orbeckst**
fix #178

### CODE REVIEW

**Comment by orbeckst** [comment]
@lilyminium I am not sure if using relative links is the right way to go about linking to jupyter notebooks. Advice is appreciated.

**Comment by orbeckst** [comment]
[According to RTD](https://mdanalysisuserguide--179.org.readthedocs.build/en/179/trajectories/transformations.html), using the relative links fixed the broken links and somehow the ugly `../` disappears from the path (maybe sphinx normalizes the paths?).

**Comment by lilyminium** [comment]
Whoops, forgot to approve. But I think relative links in Sphinx are fine; I didn't use them much because I was always a bit unsure what they were relative *to* (the actual .rst file, or `conf.py`). It looks like it's the former?

**Comment by orbeckst** [comment]
yep, looks like it

**Pull request merged**
