### PR TITLE
Update snapthots and add release notes for MDAnalysis 2.8.0

### PR DESCRIPTION
**Pull request by RMeli**
----
📚 Documentation preview 📚: https://mdanalysisuserguide--398.org.readthedocs.build/en/398/

### CODE REVIEW

**Review by lilyminium — APPROVED** [review]
LGTM for the release and CI working -- but I'm slightly confused about the snapshot tests if they are what I think they are, i.e. testing what can be read from a format... I think the original way of generating the TopologyAttr tables from the MDAnalysis tests worked well for the original paradigm, but perhaps not so well for the new guessers structure.

**Comment by lilyminium** [comment]
Thanks so much for doing this @RMeli!

**Comment by RMeli** [comment]
THB, I haven't looked closely at what the tests do, and I was just following the release instructions. I think the User Guide needs to be updated anyways for the changes of the new guessers?

**Comment by IAlibay** [comment]
Sorry not looked at the contents of this PR yet, but just wanted to chime in and say that, in my opinion, I think the user guide will need updating for the new guesser framework before a release is made. We've already had folks ask about how they should use it.

**Review by orbeckst — APPROVED** [review]
Can we just merge this and worry about more docs later?

**Comment by orbeckst** [comment]
Regarding guessers: there's PR #213

**Comment by RMeli** [comment]
Fine by me, but I think we will need to have the guesser documentation done before a `2.8.0` release? Unfortunately I have not enough knowledge about what happened during the whole GSoC project to take the lead on this. https://github.com/MDAnalysis/UserGuide/pull/213 might be stale, it was open 2 years ago.

**Comment by orbeckst** [comment]
I wouldn't hold up this PR for something that can be added later independently.

Of course it would be great to have guessers in here but that's not realistically happening in the next month or two, or does anyone think differently?

**Comment by orbeckst** [comment]
I am going to merge this PR so that other PRs won't fail because of the snapshot/guessers issue.

**Pull request merged**
